greeting:
  message: "hello"

quarkus:
  datasource:
    db-kind: mysql
    username: 
    password: 
    jdbc:
      url: 

  mp:
    jwt:
      verify:
        publickey:
          location: classpath:rsaPubKey.pem

  smallrye:
    jwt:
      sign:
        key:
          location: classpath:rsaPrivKey.pem
